from fastapi import Depends
from backend.application.use_cases.book_appointment_use_case import BookAppointmentUseCase
from backend.infrastructure.database.postgres_dependencies import get_postgres_appointment_repository

def get_book_appointment_use_case(appointment_repo = Depends(get_postgres_appointment_repository)):
    return BookAppointmentUseCase(appointment_repo=appointment_repo)